# Archivo generado automaticamente - Coordenadas

*.gateway.mobility.typename = "StationaryMobility"
*.gateway.mobility.initialX = 250m
*.gateway.mobility.initialY = 150m
*.gateway.mobility.initialZ = 0m
*.gateway.mobility.initFromDisplayString = false

*.networkServer.mobility.typename = "StationaryMobility"
*.networkServer.mobility.initialX = 400m
*.networkServer.mobility.initialY = 50m
*.networkServer.mobility.initialZ = 0m
*.networkServer.mobility.initFromDisplayString = false

*.host[0].mobility.initialX = 1048m
*.host[0].mobility.initialY = 439m
*.host[0].mobility.initialZ = 0m

*.host[1].mobility.initialX = 846m
*.host[1].mobility.initialY = 368m
*.host[1].mobility.initialZ = 0m

*.host[2].mobility.initialX = 755m
*.host[2].mobility.initialY = 320m
*.host[2].mobility.initialZ = 0m

*.host[3].mobility.initialX = 701m
*.host[3].mobility.initialY = 225m
*.host[3].mobility.initialZ = 0m

*.host[4].mobility.initialX = 480m
*.host[4].mobility.initialY = 372m
*.host[4].mobility.initialZ = 0m

*.host[5].mobility.initialX = 616m
*.host[5].mobility.initialY = 273m
*.host[5].mobility.initialZ = 0m

*.host[6].mobility.initialX = 478m
*.host[6].mobility.initialY = 294m
*.host[6].mobility.initialZ = 0m

*.host[7].mobility.initialX = 548m
*.host[7].mobility.initialY = 242m
*.host[7].mobility.initialZ = 0m

*.host[8].mobility.initialX = 631m
*.host[8].mobility.initialY = 199m
*.host[8].mobility.initialZ = 0m

*.host[9].mobility.initialX = 580m
*.host[9].mobility.initialY = 134m
*.host[9].mobility.initialZ = 0m

*.host[10].mobility.initialX = 419m
*.host[10].mobility.initialY = 283m
*.host[10].mobility.initialZ = 0m

*.host[11].mobility.initialX = 470m
*.host[11].mobility.initialY = 212m
*.host[11].mobility.initialZ = 0m

*.host[12].mobility.initialX = 375m
*.host[12].mobility.initialY = 175m
*.host[12].mobility.initialZ = 0m

*.host[13].mobility.initialX = 331m
*.host[13].mobility.initialY = 259m
*.host[13].mobility.initialZ = 0m

*.host[14].mobility.initialX = 533m
*.host[14].mobility.initialY = 27m
*.host[14].mobility.initialZ = 0m

*.host[15].mobility.initialX = 304m
*.host[15].mobility.initialY = 168m
*.host[15].mobility.initialZ = 0m

*.host[16].mobility.initialX = 289m
*.host[16].mobility.initialY = 198m
*.host[16].mobility.initialZ = 0m

*.host[17].mobility.initialX = 388m
*.host[17].mobility.initialY = 19m
*.host[17].mobility.initialZ = 0m

*.host[18].mobility.initialX = 239m
*.host[18].mobility.initialY = 153m
*.host[18].mobility.initialZ = 0m

*.host[19].mobility.initialX = 193m
*.host[19].mobility.initialY = 163m
*.host[19].mobility.initialZ = 0m

*.numHost = 20
*.width = 1198m
*.height = 494m
